development:
  encoding: unicode
  adapter: postgresql
  username: zlu
  port: 5432
  host: 127.0.0.1
  database: openvoice_development
  password: flute

test:
  encoding: unicode
  adapter: postgresql
  username: zlu
  port: 5432
  host: 127.0.0.1
  database: openvoice_test
  min_messages: WARNING
  password: flute