development:
  encoding: unicode
  adapter: postgresql
  username: zlu
  port: 5432
  host: localhost
  database: openvoice_development
  password: flute

test:
  encoding: unicode
  adapter: postgresql
  username: zlu
  port: 5432
  host: localhost
  database: openvoice_test
  min_messages: WARNING
  password: flute